# Generated by Django 3.0 on 2019-12-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_camdo'),
    ]

    operations = [
        migrations.AddField(
            model_name='camdo',
            name='image',
            field=models.ImageField(height_field=100, null=True, upload_to='', width_field=100),
        ),
    ]
