# Generated by Django 3.0 on 2019-12-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_camdo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camdo',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
