# Generated by Django 3.0 on 2019-12-10 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191210_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camdo',
            name='image',
        ),
    ]
