# Generated by Django 3.0 on 2019-12-10 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_camdo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camdo',
            name='image',
        ),
    ]
